import type { StoreData } from "./types";

export const defaultStore = (): StoreData => ({
  settings: {
    shopName: "Corner Shop",
    baseCurrency: "LAK",
    lakPerThb: 550,
    qrNote: "Scan shop QR, then tap Confirm paid",
    receiptFooter: "Thank you / ຂອບໃຈ",
    accessPin: "",
    qrImage: "",
  },
  products: [
    {
      id: "p-tee",
      name: "Cotton Tee",
      type: "clothes",
      price: 85000,
      cost: 45000,
      lowStockAt: 3,
      active: true,
      variants: [
        { id: "v-tee-m-black", sku: "TEE-M-BLK", size: "M", color: "Black", stock: 8 },
        { id: "v-tee-l-black", sku: "TEE-L-BLK", size: "L", color: "Black", stock: 5 },
        { id: "v-tee-m-white", sku: "TEE-M-WHT", size: "M", color: "White", stock: 6 },
      ],
    },
    {
      id: "p-dress",
      name: "Linen Dress",
      type: "clothes",
      price: 220000,
      cost: 120000,
      lowStockAt: 2,
      active: true,
      variants: [
        { id: "v-dress-s", sku: "DRS-S-BLU", size: "S", color: "Blue", stock: 3 },
        { id: "v-dress-m", sku: "DRS-M-BLU", size: "M", color: "Blue", stock: 4 },
      ],
    },
    {
      id: "p-candle",
      name: "Scented Candle",
      type: "gift",
      price: 65000,
      cost: 30000,
      barcode: "885012345001",
      lowStockAt: 5,
      active: true,
      variants: [{ id: "v-candle", sku: "GFT-CND-01", stock: 20 }],
    },
    {
      id: "p-mug",
      name: "Ceramic Mug",
      type: "gift",
      price: 45000,
      cost: 18000,
      lowStockAt: 5,
      active: true,
      variants: [{ id: "v-mug", sku: "GFT-MUG-01", stock: 15 }],
    },
    {
      id: "p-box-s",
      name: "Empty Box S",
      type: "box",
      price: 15000,
      cost: 5000,
      lowStockAt: 10,
      active: true,
      variants: [{ id: "v-box-s", sku: "BOX-S", size: "S", stock: 40 }],
    },
    {
      id: "p-box-m",
      name: "Empty Box M",
      type: "box",
      price: 25000,
      cost: 8000,
      lowStockAt: 10,
      active: true,
      variants: [{ id: "v-box-m", sku: "BOX-M", size: "M", stock: 30 }],
    },
    {
      id: "p-box-l",
      name: "Empty Box L",
      type: "box",
      price: 35000,
      cost: 12000,
      lowStockAt: 8,
      active: true,
      variants: [{ id: "v-box-l", sku: "BOX-L", size: "L", stock: 18 }],
    },
  ],
  orders: [],
});
